dist: xenial

language: cpp
cache: ccache
os: linux

jobs:
  include:
    - name: Linux/Doxygen, Documentation
      os: linux
      env: IMG=cnl_ci:gcc-10 SCRIPT=doc/generate.sh

script:
  - .travis/test-${TRAVIS_OS_NAME}.sh
